# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dutch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 637)
        MainWindow.setMinimumSize(QtCore.QSize(789, 637))
        MainWindow.setMaximumSize(QtCore.QSize(789, 637))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.game_widget = QtWidgets.QWidget(self.centralwidget)
        self.game_widget.setGeometry(QtCore.QRect(0, 0, 831, 651))
        self.game_widget.setStyleSheet("QWidget#game_widget{\n"
"background-color: qlineargradient(spread:pad, x1:0.095, y1:0.130545, x2:0.965, y2:0.938, stop:0 rgba(170, 85, 127, 255), stop:1 rgba(255, 255, 0, 255));}\n"
"")
        self.game_widget.setObjectName("game_widget")
        self.timer_lcd = QtWidgets.QLCDNumber(self.game_widget)
        self.timer_lcd.setGeometry(QtCore.QRect(330, 50, 151, 71))
        self.timer_lcd.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.timer_lcd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.095, y1:0.130545, x2:0.965, y2:0.938, stop:0 rgba(170, 85, 127, 255), stop:1 rgba(255, 255, 0, 255));")
        self.timer_lcd.setObjectName("timer_lcd")
        self.wordcard_label = QtWidgets.QLabel(self.game_widget)
        self.wordcard_label.setGeometry(QtCore.QRect(200, 160, 421, 251))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.wordcard_label.setFont(font)
        self.wordcard_label.setStyleSheet("border-radius:20px;background-color:rgb(170, 79, 158); font: 25pt \"Felix Titling\"; color: rgb(0, 0, 127)")
        self.wordcard_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wordcard_label.setObjectName("wordcard_label")
        self.green_button = QtWidgets.QPushButton(self.game_widget)
        self.green_button.setGeometry(QtCore.QRect(490, 460, 51, 51))
        self.green_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(0, 255, 127);")
        self.green_button.setText("")
        self.green_button.setObjectName("green_button")
        self.red_button = QtWidgets.QPushButton(self.game_widget)
        self.red_button.setGeometry(QtCore.QRect(300, 460, 51, 51))
        self.red_button.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 0, 0);")
        self.red_button.setText("")
        self.red_button.setObjectName("red_button")
        self.level_label = QtWidgets.QLabel(self.game_widget)
        self.level_label.setGeometry(QtCore.QRect(580, 40, 101, 31))
        self.level_label.setStyleSheet("font: 8pt \"Felix Titling\"; color: rgb(0, 0, 127)")
        self.level_label.setObjectName("level_label")
        self.total_time_label = QtWidgets.QLabel(self.game_widget)
        self.total_time_label.setGeometry(QtCore.QRect(360, 10, 101, 31))
        self.total_time_label.setStyleSheet("font: 8pt \"Felix Titling\"; color: rgb(0, 0, 127)")
        self.total_time_label.setObjectName("total_time_label")
        self.remaining_word_label = QtWidgets.QLabel(self.game_widget)
        self.remaining_word_label.setGeometry(QtCore.QRect(580, 80, 171, 31))
        self.remaining_word_label.setStyleSheet("font: 8pt \"Felix Titling\"; color: rgb(0, 0, 127)")
        self.remaining_word_label.setObjectName("remaining_word_label")
        self.pushButton = QtWidgets.QPushButton(self.game_widget)
        self.pushButton.setGeometry(QtCore.QRect(40, 480, 121, 41))
        self.pushButton.setStyleSheet("font: 8pt \"Felix Titling\"; color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.wordcard_label.setToolTip(_translate("MainWindow", "<html><head/><body><p>asd</p></body></html>"))
        self.wordcard_label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>English word</p></body></html>"))
        self.wordcard_label.setText(_translate("MainWindow", "Dutch\n"
"\n"
"Word"))
        self.level_label.setText(_translate("MainWindow", "Level : "))
        self.total_time_label.setText(_translate("MainWindow", "Total Time : "))
        self.remaining_word_label.setText(_translate("MainWindow", "Remaining  word : "))
        self.pushButton.setText(_translate("MainWindow", "Back to Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
